version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-security
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-runner
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-rewrite
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.14.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-web
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-1.2-api
    versions:
    - 2.14.0
